---
# tasks file for artifactory

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: collect facts about system services
  service_facts:
  register: services_state

- name: Debug
  debug:
    var: services_state
  
- name: install yum repository
  unarchive:
    url: "https://releases.jfrog.io/artifactory/jfrog-prox/org/artifactory/pro/rpm/jfrog-platform-trial-prox/[RELEASE]/jfrog-platform-trial-prox-[RELEASE]-rpm.tar.gz"
    dest: $src_dir/jfrog
  when: "ansible_facts.services['{{ service }}'] is defined"

- name: Install Artifactory
  command: ./install.sh
  environment:
    chdir: "{{ source_directory }}/jfrog-platform-trial-pro*"
  when: "ansible_facts.services['artifactory'] is defined"

- name: ensure artifactory_file_store_dir exists
  ansible.builtin.file:
    path: "{{ artifactory_file_store_dir }}"
    state: directory
    mode: "0755"
    owner: artifactory
    group: artifactory

- name: configure artifactory
  ansible.builtin.template:
    src: binarystore.xml.j2
    dest: "{{ artifactory_home }}/binarystore.xml"
    mode: "0644"
    owner: artifactory
    group: artifactory
  notify:
    - restart artifactory

- name: set ownership for artifactory_logs
  ansible.builtin.file:
    path: "{{ artifactory_logs }}"
    state: directory
    mode: "0755"
    owner: artifactory
    group: artifactory

- name: start and enable artifactory
  ansible.builtin.service:
    name: artifactory
    state: started
    enabled: yes

- name: Change the default password
  include_tasks: update_admin_passwd.yml

- name: Upload the latest License 
  include_tasks: update_license.yml
