---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check port
      wait_for:
        port: "{{ item }}"
      loop:
        - 8015
        - 8040
        - 8045
        - 8081

    - name: try webinterface
      uri:
        url: "http://localhost:8081/artifactory/webapp/"
        return_content: yes
      register: artifactory_try_webinterface
      failed_when:
        - "'Artifactory' not in artifactory_try_webinterface.content"
